import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/sessionWrapper";
import "./globalicons.css"

const workSans = Work_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased`}
      >
        <SessionWrapper>
        <Navbar/>
        {children}
        <Footer/>
        </SessionWrapper>
      </body>
    </html>
  );
}
